name: Publish Single Connector to the Ballerina Dev\Stage Central

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select Environment
        required: true
        options:
          - DEV CENTRAL
          - STAGE CENTRAL
      connector:
        type: choice
        description: Select Connector
        required: true
        options:
          - api_material_document_srv
          - api_material_stock_srv
          - api_physical_inventory_doc_srv
          - api_reservation_document_srv
          - ce_apireservationdocument_0001

jobs:
  call_workflow:
    name: Run Dev\Stage Central Publish Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/s4hana-dev-stage-central-single-publish-template.yml@main
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      hana-connector-group: inventory
      hana-connector-name: ${{ inputs.connector }}
