name: Publish Release

on:
  workflow_dispatch:
    inputs:
      connector:
        type: choice
        description: Select Connector
        required: true
        options:
          - api_material_document_srv
          - api_material_stock_srv
          - api_physical_inventory_doc_srv
          - api_reservation_document_srv
          - ce_apireservationdocument_0001

jobs:
  call_workflow:
    name: Run Release Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/s4hana-release-template.yml@main
    secrets: inherit
    with:
      hana-connector-group: inventory
      hana-connector-name: ${{ inputs.connector }}
